builds:
- env:
  - CGO_ENABLED=0
  - VER=`git describe`
  main: ./cmd/manager/main.go
  goos:
  - linux
  files:
    - deployment/**
    - config/crds/*
    - config/rbac/*
archive:
  wrap_in_directory: false
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
