language: go

go:  
  - "1.10.4"

env:
  - kb_version=1.0.7
  - gr_version=0.101.0
  - PATH=$PATH:`pwd`/kubebuilder/bin

before_install:  
  - curl -L -s https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  - curl -L -O "https://github.com/kubernetes-sigs/kubebuilder/releases/download/v${kb_version}/kubebuilder_${kb_version}_linux_amd64.tar.gz"
  - tar -zxvf kubebuilder_${kb_version}_linux_amd64.tar.gz
  - mv kubebuilder_${kb_version}_linux_amd64 kubebuilder 
  - curl -L -O "https://github.com/goreleaser/goreleaser/releases/download/v0.101.0/goreleaser_Linux_x86_64.tar.gz"
  - tar -zxvf goreleaser_Linux_x86_64.tar.gz
  - mv goreleaser $GOPATH/bin/

install:
  - dep ensure -v --vendor-only

script:
  - make
