dist: xenial

language: go

go:  
  - "1.10.4"

env:
  - kb_version=1.0.7 gr_version=0.101.0 dep_version=0.5.0 PATH=$PATH:/usr/local/kubebuilder/bin

before_install:  
  - curl -L -s https://github.com/golang/dep/releases/download/v${dep_version}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  - curl -L -O "https://github.com/kubernetes-sigs/kubebuilder/releases/download/v${kb_version}/kubebuilder_${kb_version}_linux_amd64.tar.gz"
  - tar -zxvf kubebuilder_${kb_version}_linux_amd64.tar.gz
  - mv kubebuilder_${kb_version}_linux_amd64 kubebuilder && sudo mv kubebuilder /usr/local/
  - rm kubebuilder_${kb_version}_linux_amd64.tar.gz
  - curl -L -O "https://github.com/goreleaser/goreleaser/releases/download/v${gr_version}/goreleaser_Linux_x86_64.tar.gz"
  - tar -zxvf goreleaser_Linux_x86_64.tar.gz
  - mv goreleaser $GOPATH/bin/
  - rm goreleaser_Linux_x86_64.tar.gz
  - go get github.com/mattn/goveralls

install:
  - dep ensure -v --vendor-only

script:
  - make testci
  - $GOPATH/bin/goveralls -coverprofile=cover.out -service=travis-ci
  - make managerci

deploy:
  - provider: script
    skip_cleanup: true
    script: git checkout -- README.md && goreleaser --skip-validate
    on:
      tags: true
