FROM ubuntu:cosmic

WORKDIR /go/src/github.com/DevFactory/smartnat
RUN DEBIAN_FRONTEND=noninteractive apt-get update 
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y golang-1.10 wget git vim vim-gocomplete
RUN wget https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64 -O /usr/local/bin/dep && chmod +x /usr/local/bin/dep
ENV GOPATH=/go
COPY . .
RUN dep ensure -v --vendor-only
CMD ["bash"]

