apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: mappings.smartnat.aureacentral.com
spec:
  group: smartnat.aureacentral.com
  names:
    kind: Mapping
    plural: mappings
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            addresses:
              items:
                type: string
              minItems: 1
              type: array
            allowedSources:
              items:
                type: string
              minItems: 0
              type: array
            mode:
              enum:
              - service
              type: string
            ports:
              items:
                properties:
                  port:
                    format: int32
                    maximum: 65535
                    minimum: 1
                    type: integer
                  protocol:
                    enum:
                    - tcp
                    - udp
                    type: string
                  servicePort:
                    format: int32
                    maximum: 65535
                    minimum: 1
                    type: integer
                type: object
              minItems: 1
              type: array
            serviceName:
              maxLength: 62
              minLength: 1
              type: string
          required:
          - addresses
          - allowedSources
          - serviceName
          - mode
          - ports
          type: object
        status:
          properties:
            configuredAddresses:
              type: object
            invalid:
              type: string
            serviceVIP:
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
