// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import net "net"
import v1 "k8s.io/api/core/v1"
import v1alpha1 "github.com/DevFactory/smartnat/pkg/apis/smartnat/v1alpha1"

// IPTablesHelper is an autogenerated mock type for the IPTablesHelper type
type IPTablesHelper struct {
	mock.Mock
}

// DeleteDNAT provides a mock function with given fields: externalIP, _a1
func (_m *IPTablesHelper) DeleteDNAT(externalIP net.IP, _a1 *v1alpha1.Mapping) error {
	ret := _m.Called(externalIP, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(net.IP, *v1alpha1.Mapping) error); ok {
		r0 = rf(externalIP, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteMark provides a mock function with given fields: externalIP, _a1
func (_m *IPTablesHelper) DeleteMark(externalIP net.IP, _a1 *v1alpha1.Mapping) error {
	ret := _m.Called(externalIP, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(net.IP, *v1alpha1.Mapping) error); ok {
		r0 = rf(externalIP, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteSNAT provides a mock function with given fields: externalIP, _a1
func (_m *IPTablesHelper) DeleteSNAT(externalIP net.IP, _a1 *v1alpha1.Mapping) error {
	ret := _m.Called(externalIP, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(net.IP, *v1alpha1.Mapping) error); ok {
		r0 = rf(externalIP, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetupDNAT provides a mock function with given fields: externalIP, _a1, svc, eps, setupMasquerade
func (_m *IPTablesHelper) SetupDNAT(externalIP net.IP, _a1 *v1alpha1.Mapping, svc *v1.Service, eps *v1.Endpoints, setupMasquerade bool) error {
	ret := _m.Called(externalIP, _a1, svc, eps, setupMasquerade)

	var r0 error
	if rf, ok := ret.Get(0).(func(net.IP, *v1alpha1.Mapping, *v1.Service, *v1.Endpoints, bool) error); ok {
		r0 = rf(externalIP, _a1, svc, eps, setupMasquerade)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetupMark provides a mock function with given fields: externalIP, _a1
func (_m *IPTablesHelper) SetupMark(externalIP net.IP, _a1 *v1alpha1.Mapping) error {
	ret := _m.Called(externalIP, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(net.IP, *v1alpha1.Mapping) error); ok {
		r0 = rf(externalIP, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetupSNAT provides a mock function with given fields: externalIP, _a1, svc, eps
func (_m *IPTablesHelper) SetupSNAT(externalIP net.IP, _a1 *v1alpha1.Mapping, svc *v1.Service, eps *v1.Endpoints) error {
	ret := _m.Called(externalIP, _a1, svc, eps)

	var r0 error
	if rf, ok := ret.Get(0).(func(net.IP, *v1alpha1.Mapping, *v1.Service, *v1.Endpoints) error); ok {
		r0 = rf(externalIP, _a1, svc, eps)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
