// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import v1 "k8s.io/apimachinery/pkg/apis/meta/v1"

// Namer is an autogenerated mock type for the Namer type
type Namer struct {
	mock.Mock
}

// Name provides a mock function with given fields: objectMeta
func (_m *Namer) Name(objectMeta v1.ObjectMeta) string {
	ret := _m.Called(objectMeta)

	var r0 string
	if rf, ok := ret.Get(0).(func(v1.ObjectMeta) string); ok {
		r0 = rf(objectMeta)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
